name: Latest blog post workflow
on:
  schedule:
    - cron: '0 0 * * SUN'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in medium.com posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://polaris000.medium.com/feed"
          template: "<tr><td>[$title]($url)</td><td>$date</td><td>$categories</td></tr>"
